cxx_binary(
  name = 'tests',
  header_namespace = '',
  headers = glob([
    '*.h',
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  compiler_flags = [
    '-std=c++11',
  ],
  deps = [
    '//:unittest-cpp',
  ],
)
